import Head from "next/head";
import { Inter } from "next/font/google";
import Saludo from "@/components/layout/main/saludos";
import BarraNav from "@/components/layout/header/BarraNavegador";

const inter = Inter({ subsets: ["latin"] });

export default function image() {
  return (
    <>
<Head>
         <title>COMPONENTE DE REACT</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
</Head>
<body>
    <header>
    <BarraNav/>
    </header>
     <main>
        <h1>React</h1>
        <p>ReactJS es una de las librerías más populares de JavaScript para el desarrollo de aplicaciones móviles y web.</p>
        <a href="/react/componentes">Componentes</a>
         

    </main>
    <footer></footer>
    </body>
    </>
  );
}