import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Saludo from "@/components/layout/main/saludos";
import BarraNav from "@/components/layout/header/cabeza";
import Contador from "@/components/layout/footer/contador";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <BarraNav/>

      </header>
      <main>
        <Saludo/>
        <hr />
      </main>
      <footer>
      <Contador/>
      </footer>
    </>
  );
}
