import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Saludo from "@/components/layout/main/saludos";
import BarraNav from "@/components/layout/header/cabeza";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <BarraNav/>
      </header>
      <main>
        <h1>Formulario</h1>
        <p>El formulario ("form" en inglés) se utiliza para recabar información del usuario. Se escribe 
            con &lt;form&gt; y cuenta con muchos elementos.
        </p>
        <h3>Label</h3>
        <p>

        </p>
        <form action="">
            <p>
            <label htmlFor="name">Nombre </label>
            <input type="text" name="name" />
            </p>
            <p>
                <label htmlFor="email">Correo Electrónico </label>
                <input type="email" name="email" />
            </p>
            <p>
            <label htmlFor="birthdate">Fecha nacimiento  </label>
            <input type="date" name="birthdate" />
            </p>
            <p>
                <label htmlFor="product">Producto</label>
                <select name="product" id="product">
                    <option value="libro">Libro</option>
                    <option value="lapiz">Lápiz</option>
                    <option value="caña_pesca">Caña de Pescar</option>
                    <option value="acuarela">Obra de acuarela</option>
                </select>
            </p>
            <p>
                <label htmlFor="comments">Comentarios</label> <br/>
                <textarea id="comments" name="comments" cols={30} rows={10}></textarea>
            </p>
            <p>
                <legend>¿Aceptas los criterios?</legend>
                <label><input type="radio" name="radio" value="yes" /> Si</label>
                <label><input type="radio" name="radio" value="no" /> No</label>
            </p>
            <input type="submit" value="Enviar" />
        </form>
      </main>
      <footer></footer>
    </>
  );
}