import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Saludo from "@/components/layout/main/saludos";
import BarraNav from "@/components/layout/header/BarraNavegador";

export default function Home() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
        <BarraNav/>
        </header>
        <main>
        <h1>Componentes</h1> 
         <h2> Component es la clase base para los componentes de React 
            definidos como clases en JavaScript.  </h2> 
         <h1>Ejemplo de componentes </h1> 
         <p>Hay dos tipos de componentes en React:</p>
         <ul>
            <li>Los componentes funcionales</li>
            <li>Los componentes de clase</li>
         </ul>
         <h2>Componentes funcionales</h2>
         <p>
            Funcionan como funciones en un lenguaje de programación. Aceptan inputs y devuelven outputs.
            Hay varios ejemplos:
            <ol>
                <li>

                </li>
            </ol>
         </p>
         <h2>Componentes de clase</h2>
         <p>Funciona como una clase en programación</p>
         <div>
         <a href="/">HOME</a>
         </div>
          
        </main>
        <footer>
            
        </footer>
      </>
    );
  }
  